version: '3.4'
services:
    postgres:
        image: kartoza/postgis
        environment:
            POSTGRES_USER: "gisdemo"
            POSTGRES_PASSWORD: "gisdemo"
            POSTGRES_DBNAME: "gisdemo"
        volumes:
            - ./sql/create-db.sql:/docker-entrypoint-initdb.d/setup-db.sql
        ports:
            - 5432:5432

    gisdemo:
        build: .
        depends_on:
            - postgres
        ports:
            - "8000:8000"
